[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {UserAgent = "googlebot|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|rogerbot|linkedinbot|embedly|quora link preview|showyoubot|outbrain|pinterest|slackbot|vkShare|W3C_Validator"}
  headers = {X-Prerender = "true"}
